name: TurfexCB
version: '1.0'
main: de.pixeltyles.turfexcb.TurfexCB
api-version: '1.20'

commands:
  coins:
    permission-message: §cPermission §8| §cDazu hast du keine Rechte.
    permission: coins.use
  job:
    aliases: jobs
  pay:
  supercoins:
    permission: supercoins.use
  discord:
    aliases: dc